spring.application.name=Backend
spring.datasource.url=jdbc:postgresql://localhost:5432/Hatly_DB
spring.datasource.username=postgres
spring.datasource.password=Baraa@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
jwt.secret=${JWT_SECRET}
stripe.api.key=${STRIPE_API_KEY:sk_test_4eC39HqLyjWDarjtT1zdp7dc}
stripe.webhook.secret=${STRIPE_WEBHOOK_SECRET:whsec_test_secret_key_12345}
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=ecowatchsystem@gmail.com
spring.mail.password=fpyy dixg nfwg iirp
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
aws.s3.endpoint=http://localhost:9000
aws.s3.access-key=ROOTUSER
aws.s3.secret-key=CHANGEME123
aws.s3.region=us-east-1
aws.s3.bucket-name=food-delivery-bucket
spring.data.redis.host=localhost
spring.data.redis.port=6380